### PR TITLE
logger is not defined

### PR DESCRIPTION
**Pull request by Raynos**

### CODE REVIEW

**Comment by dshaw** [comment]
<3 Thank you!

**Comment by Raynos** [comment]
@dshaw `npm version 1.0.1 && npm publish`

**Comment by dshaw** [comment]
@Raynos patience, patience. :ship:

**Comment by Raynos** [comment]
`ssh troll@dshaw.voxer.com "cd ~/projects/replify && npm version 1.0.1 && npm publish"`

**Pull request merged**
